### PR TITLE
Broaden DOI URLpattern to other resolver variants

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff & https://www.doi.org/doi_handbook/3_Resolution.html#3.8 ;-)

There may be at least 4 different, but officially supported DOI resolver URLs floating around. This PR broadens a reg-ex to catch them all.

### CODE REVIEW

**Comment by TomWeishaar** [comment]
Thank you. Sorry it took me so long to notice you'd left this. It's my first pull request!

**Comment by katrinleinweber** [comment]
🎉 You're welcome, and thanks for merging :-)

**Comment by TomWeishaar** [comment]
Katrin - in your regex, R wants an escape backslash before the existing backslash, so, although regex is one of my weak areas, I think it would be:

`"https?://(dx\\.)?doi.org/"`

In trying to figure this out I was looking for the four URLs you mentioned but I could only find these three:

doi.org
dx.doi.org
shortdoi.org

Your regex doesn't match shortdoi.org. I was thinking of changing it to "http.+doi.org/" (ie, anything that begins with "http" and ends with "doi.org/", but I'm not sure what the other two URLs are that we need to match.

For any others who read this, the context of the code Katrin improved is that it's looking for a fragment in a string that has a doi URL in it. Then we want to trim off the domain part of the URL and anything in the string before it, leaving only the DOI code. (There could also be more text after that, which also gets trimmed off.)

**Comment by TomWeishaar** [comment]
Oh, wait, I get it. Your four URLs are `http` or `https` plus `doi.org` or `dx.doi.org`.

Let me know if you see a problem with `"http.+doi.org/"` as the regex. - Tom

**Comment by katrinleinweber** [comment]
Yes, I had only considered the 4 variants of `doi.org`, not `shortdoi.org`. `http.+doi.org/` is a good idea, but it would also capture any other `evildoi.org` domain.

I would get [explicit `https?://(dx[.])?(short)?doi[.]org`](https://regexr.com/40b90), this time making the `.` literal in a way that doesn't rely on double-escaping. Because I made a typo initially: only a single `\` before the `.` m-(

**Comment by TomWeishaar** [comment]
Thanks Katrin - The code now has your last update. - Tom

**Comment by katrinleinweber** [comment]
Cool! I'd be curious to learn how this fares over time :-) I have not experience so far with using the `(short)?` part.

**Pull request merged**
